# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Naeima Hamed
author: Naeima Hamed
logo: Naeima.png
extra_navbar: |
  - [<img src='https://cdn-icons-png.flaticon.com/512/145/145807.png' width='16'> LinkedIn](https://www.linkedin.com/in/naeima-hamed-ba553041/)  
  - [<img src='https://cdn-icons-png.flaticon.com/512/3041/3041533.png' width='16'> ResearchGate](https://www.researchgate.net/profile/Naeima-Hamed)  
  - [<img src='https://cdn-icons-png.flaticon.com/512/2427/2427326.png' width='16'> Research Website](https://ontology.forest-observatory.cardiff.ac.uk)  
  - [<img src='https://cdn-icons-png.flaticon.com/512/2206/2206243.png' width='16'> Chat with Me](https://naeima.zapier.app/chat?trk=public_post_embed_feed-article-content)
  - [Chat with Me](#) <script async type="module" src="https://interfaces.zapier.com/assets/web-components/zapier-interfaces/zapier-interfaces.esm.js"></script>
  <zapier-interfaces-chatbot-embed is-popup="true" chatbot-id="clwdn1i7p0005b3tk59w8pdsd"></zapier-interfaces-chatbot-embed>


# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the LaTeX output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a BibTeX file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/Naeima/Naeima  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)
# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
 
